version: 2.1

jobs:
  build: 
        
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - checkout
      - run:
          name: Install packages 
          command: npm install
      - run:
          name: Install Allure 
          command: npm install -g allure-commandline --save-dev
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  test-course:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests Course project
          # command: npm run test:course
          command: npx cypress run --spec ./cypress/integration/courseProject/1*.feature --env allure=true
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - allure-results
            - cypress/videos
  test-graduation:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests Graduation project
          # command: npm run test:graduation
          command: npx cypress run --spec ./cypress/integration/graduationProject/1*.feature --env allure=true
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - allure-results
            - cypress/videos
  generate_report:
    working_directory: ~/tmp
    docker:
      - image: 'frankescobar/allure-docker-service'
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate report 
          command: allure generate ./allure-results --clean -o allure-report
      - store_artifacts:
          path: allure-report
      - persist_to_workspace:
          root: ~/
          paths:
            - allure-report
  deploy:
    working_directory: ~/
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy report 
          # git rm -rf . !(".git")
          # git remote add origin https://anisovichBNTU:anisovichBNTUcypress@github.com/anisovichBNTU/bntu-cypress-framework.git
          command: |
            git config --global user.email anisovich28@gmail.com
            git config --global user.name anisovichBNTU

            git clone https://github.com/anisovichBNTU/bntu-cypress-framework.git out
            
            cd out
            git remote add deploy https://anisovichBNTU:anisovichBNTUcypress@github.com/anisovichBNTU/bntu-cypress-framework.git
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cd ..

            cp -a allure-report out/.
            cd out

            git add ./allure-report
            git commit -m "Automated deployment to GitHub Pages" --allow-empty

            git push deploy gh-pages

workflows:
  build_and_test:
    jobs:
      - build
      - test-course:
          requires:
            - build
      - test-graduation:
          requires:
            - build
      - approval-report:
          type: approval
      - generate_report:
          requires:
            - approval-report
      - deploy:
          requires:
            - generate_report
