version: 2.1

jobs:
  build:    
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - checkout
      - run:
          name: Install packages 
          command: npm install
      - run:
          name: Install Allure 
          command: npm install -g allure-commandline --save-dev
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  test-course:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests Course project
          command: npm run test:course
          # command: npx cypress run --spec ./cypress/integration/courseProject/1*.feature --env allure=true
      - run: 
          name: Push results 
          when: always
          command: |
            git config --global user.email anisovich28@gmail.com
            git config --global user.name anisovichBNTU

            git clone https://github.com/anisovichBNTU/bntu-cypress-framework.git out
            
            cd out
            git remote add results https://anisovichBNTU:anisovichBNTUcypress@github.com/anisovichBNTU/bntu-cypress-framework.git
            git checkout allure-results1 || git checkout --orphan allure-results1
            git rm -rf .
            cd ..

            cp -a allure-results out/.
            cp -a cypress/videos out/.
            cd out

            git add ./allure-results
            git commit -m "Push results 1" --allow-empty

            git push results allure-results1
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - ./allure-results/
  test-interactive:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests Interactive book
          command: npm run test:interactive
          # command: npx cypress run --spec ./cypress/integration/courseProject/1*.feature --env allure=true
      - run: 
          name: Push results 
          when: always
          command: |
            git config --global user.email anisovich28@gmail.com
            git config --global user.name anisovichBNTU

            git clone https://github.com/anisovichBNTU/bntu-cypress-framework.git out
            
            cd out
            git remote add results https://anisovichBNTU:anisovichBNTUcypress@github.com/anisovichBNTU/bntu-cypress-framework.git
            git checkout allure-results3 || git checkout --orphan allure-results3
            git rm -rf .
            cd ..

            cp -a allure-results out/.
            cp -a cypress/videos out/.
            cd out

            git add ./allure-results
            git commit -m "Push results 3" --allow-empty

            git push results allure-results3
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - ./allure-results/
  test-graduation:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests Graduation project
          command: npm run test:graduation
      - run: 
          name: Push results 
          when: always
          command: |
            git config --global user.email anisovich28@gmail.com
            git config --global user.name anisovichBNTU

            git clone https://github.com/anisovichBNTU/bntu-cypress-framework.git out
            
            cd out
            git remote add results https://anisovichBNTU:anisovichBNTUcypress@github.com/anisovichBNTU/bntu-cypress-framework.git
            git checkout allure-results2 || git checkout --orphan allure-results2
            git rm -rf .
            cd ..

            cp -a allure-results out/.
            cp -a cypress/videos out/.
            cd out

            git add ./allure-results
            git commit -m "Push results 2" --allow-empty

            git push results allure-results2
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - ./allure-results/
  test-eemc:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests EEMC
          command: npm run test:eemc
      - run: 
          name: Push results 
          when: always
          command: |
            git config --global user.email anisovich28@gmail.com
            git config --global user.name anisovichBNTU

            git clone https://github.com/anisovichBNTU/bntu-cypress-framework.git out
            
            cd out
            git remote add results https://anisovichBNTU:anisovichBNTUcypress@github.com/anisovichBNTU/bntu-cypress-framework.git
            git checkout allure-results4 || git checkout --orphan allure-results4
            git rm -rf .
            cd ..

            cp -a allure-results out/.
            cp -a cypress/videos out/.
            cd out

            git add ./allure-results
            git commit -m "Push results 4" --allow-empty

            git push results allure-results4
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - ./allure-results/
  combine_reports:
    working_directory: ~/
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Combine report
          command: |
            git config --global user.email anisovich28@gmail.com
            git config --global user.name anisovichBNTU

            git clone https://github.com/anisovichBNTU/bntu-cypress-framework.git out
            
            cd out
            git checkout allure-results1 || git checkout --orphan allure-results1
            cp -a allure-results ../
            cp -a cypress ../
            git checkout allure-results2 || git checkout --orphan allure-results2
            cp -a allure-results ../
            cp -a cypress ../
            git checkout allure-results3 || git checkout --orphan allure-results3
            cp -a allure-results ../
            git checkout allure-results4 || git checkout --orphan allure-results4
            cp -a allure-results ../
            cp -a cypress ../
      - persist_to_workspace:
          root: ~/
          paths:
            - allure-results      
  generate_report:
    working_directory: ~/
    docker:
      - image: 'frankescobar/allure-docker-service'
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate report 
          command: allure generate -c allure-results --clean -o allure-report
      - store_artifacts:
          path: allure-report
      - persist_to_workspace:
          root: ~/
          paths:
            - allure-report
  deploy:
    working_directory: ~/
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy report 
          command: |
            git config --global user.email anisovich28@gmail.com
            git config --global user.name anisovichBNTU

            git clone https://github.com/anisovichBNTU/bntu-cypress-framework.git out
            
            cd out
            git remote add deploy https://anisovichBNTU:anisovichBNTUcypress@github.com/anisovichBNTU/bntu-cypress-framework.git
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cd ..

            cp -a allure-report out/.
            cd out

            git add ./allure-report
            git commit -m "Automated deployment to GitHub Pages" --allow-empty

            git push deploy gh-pages

workflows:
  build_and_test:
    jobs:
      - build
      - test-course:
          requires:
            - build
      - test-graduation:
          requires:
            - build
      - test-interactive:
          requires:
            - build
      - test-eemc:
          requires:
            - build
      - approval-report:
          type: approval
      - combine_reports:
          requires:
            - approval-report
      - generate_report:
          requires:
            - combine_reports
      - deploy:
          requires:
            - generate_report
