version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - checkout
      - run:
          name: Install packages 
          command: npm install
      - run:
          name: Install Allure 
          command: npm install -g allure-commandline --save-dev
      - restore_cache:
          keys:
            - 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
            - 'v2-deps-{{ .Branch }}-'
            - v2-deps-
      - save_cache:
          key: 'v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}'
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - tmp
  test-course:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests Course project
          command: npm run test:course
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/
          paths:
            - allure-results
            - cypress/videos

  test-graduation:  
    working_directory: ~/tmp
    docker:
      - image: cypress/base:14.16.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run tests Graduation project
          command: npm run test:graduation
      - store_artifacts:
          path: allure-results
      - store_artifacts:
          path: cypress/videos
      - persist_to_workspace:
          root: ~/
          paths:
            - allure-results
            - cypress/videos
  generate_report:
    working_directory: ~/tmp
    docker:
      - image: 'cypress/base:14.16.0'
    steps:
      - run:
          name: Generate report 
          command: allure generate allure-results --clean -o allure-report
      - attach_workspace:
          at: /tmp/allure-report
      - persist_to_workspace:
          root: ~/
          paths:
            - allure-report
            - allure-results
            - cypress/videos
workflows:
  build_and_test:
    jobs:
      - build
      - test-course:
          requires:
            - build
      - test-graduation:
          requires:
            - build
      - generate_report:
          requires:
            - test-course
            - test-graduation
